# Generated by Django 2.0.3 on 2018-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_id',
            field=models.SlugField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
